name = "The Beast Reborn"
author = "Grace & Friends"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29bdb66b6856f3810007f8152783ef9a5363492200922a7814c0313d1cc279e0"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
