name = "The Beast Reborn"
author = "Grace & Friends"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e800346f7e2445e87a9668f52d585a8816179bf0abd81e1370d431b589e68a10"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
