name = "The Beast Reborn"
author = "Grace & Friends"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4cba7d6bd57cfb94121cf5a48ab57f91081085ec7f2ec945d40778a6618838a"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
