name = "The Beast Reborn"
author = "Grace & Friends"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b49665e4c9ddbf8b57a9eb5db97fdfc85ec26dac87e51d90a54405fbfe00219b"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
