name = "The Beast Reborn"
author = "Grace & Friends"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64d107af0958e779d54f320a088be5e75379079cb716ca76a55bc40b0d0d09d9"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
