name = "The Beast Reborn"
author = "Grace & Friends"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79c339a576b15baad89cffb632435dce495376537eb1cb213c04266dd35fa113"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
