name = "The Beast Reborn"
author = "Grace & Friends"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9825818244699ebe23e830ace403e8895725ece088a6fe7bd87b9645e8c6c5ab"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
