name = "The Beast Reborn"
author = "Grace & Friends"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1b6fdd417127908b7d02c3f8e3d13e5dfdccde01b376c73705cfcdcb1a83959"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
