name = "The Beast Reborn"
author = "Grace & Friends"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aca04c027e0233c12575b26d90c4c0f99d1db02af238aa22b52e105e460be83d"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
