name = "The Beast Reborn"
author = "Grace & Friends"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b1dca3564272e377bb1e0ab11f0b30146b88c12aebbb0ff12f134daa4175b27"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
