name = "The Beast Reborn"
author = "Grace & Friends"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab6aad236233c274044a365b0c8ac2912d7df27dd6e57909df1e4c6073c487a7"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
